name: Fun Check
on:
  repository_dispatch:
    types: trigger-on-release
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  pr_comment:
    runs-on: ubuntu-20.04
    if: github.event.issue.pull_request && contains(github.event.comment.body,'/Fun')
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Check the git branch
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse --verify HEAD
        shell: bash

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
