name: Fun Check
on:
  repository_dispatch:
    types: trigger-on-release
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: write
  statuses: write

jobs:
  pr_comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body,'/Fun')
    runs-on: ubuntu-20.04
    steps:
      # - uses: xt0rted/pull-request-comment-branch@v3
      #   id: comment-branch
      - name: Get Github SHA
        id: sha
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const { owner,repo,number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.sha.outputs.result }}

      - name: Check the git branch
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse --verify HEAD
        shell: bash

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.sha.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: Construct comment
        uses: actions/github-script@v7
        if: always()
        id: comment
        with:
          result-encoding: string
          script: |
            const name ${{ github.workflow   }}
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}`;
            return body

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        if: always()
        with:
          comment-id: ${{github.event.comment.id}}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi this is from peter evans
            ${{ github.workflow   }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ steps.comment.outputs.result}}
          edit-mode: replace
